#!/usr/bin/env perl

use strict;
use warnings;
use integer;

use Scalar::Util qw(looks_like_number);
use List::Util qw(reduce);

my $filename = 'input_1';
open (my $fh, '<:encoding(UTF-8)', $filename)
    or die "Could not open '$filename' $!";

my $result = reduce { $a +  getFuel($b) } 0, <$fh>;
print $result;

sub getFuel {
    my ($weight) = @_;
    $weight = $weight/3 - 2;

    if ($weight <= 0) {
        return 0;
    }

    #Comment out for part 1
    $weight = $weight + getFuel($weight);

    return $weight;
}
